config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  
  resources :products
  
  resources :categories , param: :category_id do
    #collection 跟 member 差異在於 m要參數,c 不用。
    collection do
#      get :products
    end
    
    #所以member就是 show 的概念 後面再加上你要新增的URL
    member do 
      get :products
      
      resources :subcategories ,param: :subcategory_id,only: [:index] do 
        member do 
           get :products
        end
      end
      
    end
  end
  
  #因為用不到create edit delete等功能,所以用舊方法製造路徑。
  get "admin/log_in" , to: "admin#log_in"
  #get "admin/log_in" /// "admin/log_out"  只會顯示頁面,他並不會有其他多餘的動作,所以我們還要一個post。 那至於登出就登出了,所以不需要post
  post "admin/create_session" , to: "admin#create_session"
  get "admin/log_out" , to: "admin#log_out"
end

app/views/layouts/_footer.html.erb
<footer class="jumbotron" style="margin-bottom:0; color:white; background-color:black;">
  <h6 style="margin:10px">
    <p>銷售據點</p>
    <p>聯絡方式</p>
    <p>熱銷產品</p>
  </h6>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar">1</span>
        <span class="icon-bar">2</span>
        <span class="icon-bar">3</span>
      </button>
      <%= link_to "PSGB",root_path,class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">熱銷人身部品<span class="sr-only">(current)</span></a></li>
        <li><a href="#">新品上市</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">銷售據點 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">台北-信義區-911STORE</a></li>
            <li><a href="#">台中-西屯區-BC門市</a></li>
            <li><a href="#">高雄-鳳山-PSGB直營店</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">香港-蝴蝶灣-蛋塔Helmet門市</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">美國-洛杉磯-Bootstab門市</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">搜尋</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">註冊</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">會員專區<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if current_user %>
              <li>
                <%= link_to "新增商品" , new_product_path %>
              </li>
              <li>
                <%= link_to "登出" ,admin_log_out_path %>
              </li>
            <% else%>
              <%= link_to "登入會員" ,admin_log_in_path %>
            <% end %>
            <li><a href="#">剩餘點數</a></li>
            <li><a href="#">購買紀錄</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">退款進度</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>work1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%=  render partial: "layouts/nav"%>
    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
    <%=  render partial: "layouts/footer"%>
  </body>
</html>